import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, History, Play, Plus, Wrench } from 'lucide-react';
import { useFarm } from '../../context/FarmContext';
import { useAuth } from '../../context/AuthContext';
import { useI18n } from '../../i18n';
import { maintenanceRoleAllows } from '../../utils/maintenanceAccess';
import {
  completeMaintenanceWorkOrder, createMaintenanceWorkOrder, listMaintenanceEvents, listMaintenanceWorkOrders,
  MaintenanceEvent, MaintenancePartUsage, MaintenanceWorkOrder, startMaintenanceWorkOrder,
} from '../../services/maintenanceService';

function localDate(): string { const d = new Date(); const pad = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; }

export const MaintenanceView: React.FC = () => {
  const { equipment } = useFarm();
  const { currentUser } = useAuth();
  const { formatDate, formatNumber } = useI18n();
  const [orders, setOrders] = useState<MaintenanceWorkOrder[]>([]);
  const [events, setEvents] = useState<MaintenanceEvent[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [code, setCode] = useState(''); const [equipmentId, setEquipmentId] = useState(equipment[0]?.id || ''); const [type, setType] = useState<MaintenanceWorkOrder['type']>('Preventive');
  const [priority, setPriority] = useState<MaintenanceWorkOrder['priority']>('Normal'); const [description, setDescription] = useState(''); const [technician, setTechnician] = useState(''); const [plannedDate, setPlannedDate] = useState(localDate()); const [failureReason, setFailureReason] = useState('');
  const [resolution, setResolution] = useState(''); const [downtime, setDowntime] = useState('0'); const [laborCost, setLaborCost] = useState('0'); const [nextServiceDate, setNextServiceDate] = useState('');
  const [parts, setParts] = useState<MaintenancePartUsage[]>([]); const [partName, setPartName] = useState(''); const [partQty, setPartQty] = useState('1'); const [partUnit, setPartUnit] = useState('pcs'); const [partCost, setPartCost] = useState('0');
  const role = String(currentUser?.role || ''); const canCreate = maintenanceRoleAllows(role, 'create'); const canEdit = maintenanceRoleAllows(role, 'edit'); const canApprove = maintenanceRoleAllows(role, 'approve');
  const selected = orders.find((row) => row.id === selectedId);

  const refresh = async () => { try { const rows = await listMaintenanceWorkOrders(); setOrders(rows); if (!selectedId && rows[0]) setSelectedId(rows[0].id); } catch (e) { setError(e instanceof Error ? e.message : 'MAINTENANCE_LOAD_FAILED'); } };
  const refreshEvents = async (id = selectedId) => { if (!id) return setEvents([]); try { setEvents(await listMaintenanceEvents(id)); } catch { setEvents([]); } };
  useEffect(() => { void refresh(); }, []); useEffect(() => { void refreshEvents(); }, [selectedId]);
  const run = async (task: () => Promise<any>, text: string) => { if (busy) return; setBusy(true); setError(''); setMessage(''); try { const payload = await task(); const row = payload.workOrder as MaintenanceWorkOrder; setOrders((prev) => prev.some((x) => x.id === row.id) ? prev.map((x) => x.id === row.id ? row : x) : [row, ...prev]); setSelectedId(row.id); setMessage(text); await refreshEvents(row.id); } catch (e) { setError(e instanceof Error ? e.message : 'MAINTENANCE_REQUEST_FAILED'); } finally { setBusy(false); } };
  const stats = useMemo(() => ({ open: orders.filter((o)=>o.status==='OPEN').length, active: orders.filter((o)=>o.status==='IN_PROGRESS').length, overdue: orders.filter((o)=>['OPEN','IN_PROGRESS'].includes(o.status) && o.plannedDate < localDate()).length, cost: orders.filter((o)=>o.status==='COMPLETED').reduce((s,o)=>s+o.totalCost,0) }), [orders]);
  const addPart = () => { const q=Number(partQty), c=Number(partCost); if(!partName.trim()||!partUnit.trim()||!Number.isFinite(q)||q<=0||!Number.isFinite(c)||c<0) return; setParts((p)=>[...p,{name:partName.trim(),quantity:q,unit:partUnit.trim(),unitCost:c}]); setPartName(''); setPartQty('1'); setPartCost('0'); };

  return <div className="space-y-5 pb-12">
    <div className="bg-[#121214] border border-[#27272A] rounded-2xl p-5"><h1 className="text-lg font-black text-white flex items-center gap-2"><Wrench className="w-5 h-5 text-[#D4AF37]"/>مرکز نگهداری و تعمیرات</h1><p className="text-xs text-[#71717A] mt-1">PM، Work Order، خرابی، Downtime، هزینه و قطعات ثبت‌شده با تاریخچه عملیاتی</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Open',stats.open],['In progress',stats.active],['Overdue',stats.overdue],['هزینه تکمیل‌شده',stats.cost]].map(([l,v])=><div key={String(l)} className="bg-[#121214] border border-[#27272A] rounded-2xl p-4"><div className="text-xs text-[#71717A]">{l}</div><div className="mt-2 text-xl font-black text-white">{formatNumber(Number(v))}</div></div>)}</div>
    {message&&<div className="p-3 rounded-xl border border-emerald-500/30 bg-emerald-500/10 text-xs text-emerald-200">{message}</div>}{error&&<div className="p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-xs text-red-200">{error}</div>}
    <div className="grid xl:grid-cols-[1fr_1.35fr] gap-5">
      <div className="space-y-5">
        <div className="bg-[#121214] border border-[#27272A] rounded-2xl p-4 space-y-3"><div className="text-sm font-bold text-white flex gap-2 items-center"><Plus className="w-4 h-4"/>Work Order جدید</div>
          <div className="grid grid-cols-2 gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="WO code" className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/><input type="date" value={plannedDate} onChange={e=>setPlannedDate(e.target.value)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/></div>
          <select value={equipmentId} onChange={e=>setEquipmentId(e.target.value)} className="w-full bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs">{equipment.map(e=><option key={e.id} value={e.id}>{e.code} · {e.name}</option>)}</select>
          <div className="grid grid-cols-2 gap-2"><select value={type} onChange={e=>setType(e.target.value as any)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs">{['Preventive','Corrective','Inspection','Emergency'].map(v=><option key={v}>{v}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as any)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs">{['Low','Normal','High','Critical'].map(v=><option key={v}>{v}</option>)}</select></div>
          <input value={technician} onChange={e=>setTechnician(e.target.value)} placeholder="تکنسین/مسئول" className="w-full bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="شرح کار" className="w-full min-h-20 bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/>{['Corrective','Emergency'].includes(type)&&<input value={failureReason} onChange={e=>setFailureReason(e.target.value)} placeholder="شرح خرابی" className="w-full bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/>}
          <button disabled={!canCreate||busy} onClick={()=>void run(()=>createMaintenanceWorkOrder({code,equipmentId,type,priority,description,assignedTechnician:technician,plannedDate,failureReason}), 'Work Order ثبت شد.')} className="w-full py-2 rounded-lg bg-[#D4AF37] text-black text-xs font-bold disabled:opacity-40">ثبت Work Order</button>
        </div>
        <div className="bg-[#121214] border border-[#27272A] rounded-2xl overflow-hidden"><div className="p-4 border-b border-[#27272A] text-sm font-bold text-white">Work Orderها</div><div className="max-h-[520px] overflow-auto divide-y divide-[#27272A]">{orders.map(o=><button key={o.id} onClick={()=>setSelectedId(o.id)} className={`w-full text-start p-3 text-xs ${selectedId===o.id?'bg-[#D4AF37]/10':'hover:bg-[#18181B]'}`}><div className="flex justify-between"><span className="font-bold text-white">{o.code} · {o.equipmentCode}</span><span>{o.status}</span></div><div className="text-[#71717A] mt-1">{o.type} · {o.priority} · {o.plannedDate}</div></button>)}</div></div>
      </div>
      <div className="space-y-5"><div className="bg-[#121214] border border-[#27272A] rounded-2xl p-4 space-y-4"><div className="text-sm font-bold text-white">اجرای Work Order</div>{!selected?<div className="text-xs text-[#71717A]">موردی انتخاب نشده.</div>:<>
        <div className="bg-[#0C0C0E] border border-[#27272A] rounded-xl p-3 text-xs"><div className="font-bold text-white">{selected.code} · {selected.equipmentName}</div><div className="text-[#71717A] mt-1">{selected.description}</div>{selected.plannedDate<localDate()&&['OPEN','IN_PROGRESS'].includes(selected.status)&&<div className="mt-2 text-red-300 flex items-center gap-1"><AlertTriangle className="w-3 h-3"/>Overdue</div>}</div>
        {selected.status==='OPEN'&&<button disabled={!canEdit||busy} onClick={()=>void run(()=>startMaintenanceWorkOrder(selected.id),'کار شروع شد.')} className="w-full py-2 rounded-lg border border-[#D4AF37]/40 text-[#D4AF37] text-xs font-bold flex justify-center items-center gap-2 disabled:opacity-40"><Play className="w-4 h-4"/>Start</button>}
        {selected.status==='IN_PROGRESS'&&<><textarea value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="شرح رفع عیب/نتیجه سرویس" className="w-full min-h-20 bg-[#09090B] border border-[#3F3F46] rounded-lg px-3 py-2 text-xs"/><div className="grid grid-cols-3 gap-2"><input type="number" min="0" step="0.1" value={downtime} onChange={e=>setDowntime(e.target.value)} placeholder="Downtime h" className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/><input type="number" min="0" step="0.01" value={laborCost} onChange={e=>setLaborCost(e.target.value)} placeholder="Labor cost" className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/><input type="date" value={nextServiceDate} onChange={e=>setNextServiceDate(e.target.value)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/></div>
          <div className="border border-[#27272A] rounded-xl p-3 space-y-2"><div className="text-xs font-bold text-white">قطعات مصرفی ثبت‌شده</div><div className="grid grid-cols-4 gap-2"><input value={partName} onChange={e=>setPartName(e.target.value)} placeholder="قطعه" className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/><input type="number" value={partQty} onChange={e=>setPartQty(e.target.value)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/><input value={partUnit} onChange={e=>setPartUnit(e.target.value)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/><input type="number" value={partCost} onChange={e=>setPartCost(e.target.value)} className="bg-[#09090B] border border-[#3F3F46] rounded-lg px-2 py-2 text-xs"/></div><button onClick={addPart} className="text-xs text-[#D4AF37]">+ ثبت قطعه در Work Order</button>{parts.map((p,i)=><div key={i} className="text-[11px] text-[#A1A1AA]">{p.name}: {p.quantity} {p.unit} × {p.unitCost}</div>)}</div>
          <button disabled={!canApprove||busy} onClick={()=>void run(()=>completeMaintenanceWorkOrder(selected.id,{resolution,downtimeHours:Number(downtime),laborCost:Number(laborCost),parts,nextServiceDate:nextServiceDate||undefined}),'Work Order تکمیل و بسته شد.')} className="w-full py-2 rounded-lg bg-emerald-500/15 border border-emerald-500/40 text-emerald-200 text-xs font-bold disabled:opacity-40 flex justify-center items-center gap-2"><CheckCircle2 className="w-4 h-4"/>Complete / Approve</button></>}
        {selected.status==='COMPLETED'&&<div className="rounded-xl border border-emerald-500/30 p-3 text-xs text-[#A1A1AA]">Resolution: {selected.resolution}<br/>Downtime: {selected.downtimeHours} h · Cost: {selected.totalCost}{selected.nextServiceDate&&<><br/>Next service: {selected.nextServiceDate}</>}</div>}
      </>}</div>
      <div className="bg-[#121214] border border-[#27272A] rounded-2xl overflow-hidden"><div className="p-4 border-b border-[#27272A] text-sm font-bold text-white flex gap-2 items-center"><History className="w-4 h-4 text-[#D4AF37]"/>تاریخچه</div><div className="divide-y divide-[#27272A]">{events.length?events.map(e=><div key={e.id} className="p-3 text-xs"><div className="flex justify-between"><span className="font-bold text-white">{e.eventType}</span><span className="text-[#71717A]">{formatDate(e.timestamp)}</span></div><div className="text-[#A1A1AA] mt-1">{e.actor} · {e.notes}</div></div>):<div className="p-8 text-center text-xs text-[#71717A]">تاریخچه‌ای نیست.</div>}</div></div></div>
    </div>
    <div className="text-[11px] text-[#71717A] border border-[#27272A] rounded-xl p-3">قطعات این فرم فقط در Ledger تعمیرات و هزینه ثبت می‌شوند و موجودی Warehouse را خودکار تغییر نمی‌دهند؛ کاهش موجودی باید از تراکنش انبار انجام شود تا conservation دور زده نشود.</div>
  </div>;
};
