import React from 'react';
import { useI18n } from '../../i18n';
import { useAuth } from '../../context/AuthContext';
import { useFarm } from '../../context/FarmContext';
import { useModuleConfig } from '../../context/ModuleConfigContext';
import { LayoutDashboard,Building2,Fish,Utensils,TrendingUp,Activity,Skull,Stethoscope,ArrowLeftRight,Egg,Sparkles,Factory,Package,FlaskConical,Scissors,Snowflake,Users,Receipt,Calculator,UserCheck,Bot,Megaphone,Wrench,FileSpreadsheet,ShieldCheck,Database,Smartphone,Settings } from 'lucide-react';
import { PermissionModule } from '../../types';
interface Props{currentView:string;onSelectNav:(id:string)=>void;isOpenMobile:boolean;onCloseMobile:()=>void}
type Item={id:string;key:string;icon:React.ElementType;module:PermissionModule};
export const Sidebar:React.FC<Props>=({currentView,onSelectNav,isOpenMobile,onCloseMobile})=>{
 const {t,dir}=useI18n(); const {hasPermission,currentUser}=useAuth(); const {syncStatus}=useFarm(); const {isEnabled}=useModuleConfig();
 const admin=currentUser?.role==='Super Admin'||currentUser?.role==='Farm Owner';
 const sections:{title:string;items:Item[]}[]=[
 {title:'nav.sectionBreeding',items:[['dashboard','nav.dashboard',LayoutDashboard,'dashboard'],['farmHalls','nav.farmHalls',Building2,'halls'],['ponds','nav.ponds',Fish,'ponds'],['feeding','nav.feeding',Utensils,'feeding'],['biometrics','nav.biometrics',TrendingUp,'biometrics'],['waterQuality','nav.waterQuality',Activity,'water_quality'],['mortality','nav.mortality',Skull,'mortality'],['treatments','nav.treatments',Stethoscope,'treatments'],['transfers','nav.transfers',ArrowLeftRight,'transfers']].map(x=>({id:x[0] as string,key:x[1] as string,icon:x[2] as React.ElementType,module:x[3] as PermissionModule}))},
 {title:'nav.sectionHatchery',items:[['hatchery','nav.hatchery',Egg,'hatchery'],['nursery','nav.nursery',Sparkles,'nursery'],['feedFactory','nav.feedFactory',Factory,'feed_factory'],['warehouse','nav.warehouse',Package,'warehouse'],['laboratory','nav.laboratory',FlaskConical,'laboratory'],['processing','nav.processing',Scissors,'processing'],['coldStorage','nav.coldStorage',Snowflake,'cold_storage']].map(x=>({id:x[0] as string,key:x[1] as string,icon:x[2] as React.ElementType,module:x[3] as PermissionModule}))},
 {title:'nav.sectionCommercial',items:[['crm','nav.crm',Users,'crm'],['sales','nav.sales',Receipt,'sales'],['accounting','nav.accounting',Calculator,'accounting'],['hr','nav.hr',UserCheck,'hr']].map(x=>({id:x[0] as string,key:x[1] as string,icon:x[2] as React.ElementType,module:x[3] as PermissionModule}))},
 {title:'nav.sectionSystem',items:[['aiAssistant','nav.aiAssistant',Bot,'ai_assistant'],['mediaStudio','nav.mediaStudio',Megaphone,'media'],['maintenance','nav.maintenance',Wrench,'settings'],['reports','nav.reports',FileSpreadsheet,'reports'],['securityAudit','nav.securityAudit',ShieldCheck,'users'],['backup','nav.backup',Database,'backup'],['platformHub','nav.platformHub',Smartphone,'settings']].map(x=>({id:x[0] as string,key:x[1] as string,icon:x[2] as React.ElementType,module:x[3] as PermissionModule}))},
 ];
 if(admin) sections[3].items.push({id:'adminSettings',key:'تنظیمات ادمین',icon:Settings,module:'settings'});
 return <><div onClick={onCloseMobile} className={`${isOpenMobile?'fixed':'hidden'} inset-0 bg-black/80 z-40 lg:hidden`}/><aside className={`fixed lg:sticky top-[64px] bottom-0 ${dir==='rtl'?'right-0':'left-0'} z-40 w-[245px] bg-[#121214] border-x border-[#1F1F22] flex flex-col h-[calc(100vh-64px)] transition-transform ${isOpenMobile?'translate-x-0':dir==='rtl'?'translate-x-full lg:translate-x-0':'-translate-x-full lg:translate-x-0'}`}><div className="flex-1 overflow-y-auto px-3 py-4 space-y-5">{sections.map(s=>{const items=s.items.filter(i=>isEnabled(i.id)&&hasPermission(i.module,'view'));if(!items.length)return null;return <div key={s.title}><h3 className="px-3 text-[10px] uppercase tracking-widest text-[#71717A] mb-2">{t(s.title)}</h3><nav className="space-y-1">{items.map(i=>{const I=i.icon,a=currentView===i.id;return <button key={i.id} onClick={()=>{onSelectNav(i.id);onCloseMobile()}} className={`w-full flex items-center gap-2.5 px-3 py-2 text-xs rounded-lg ${a?'bg-[#1F1F22] text-[#D4AF37] border border-[#D4AF37]/30':'text-[#A1A1AA] hover:bg-[#1F1F22]'}`}><I className="w-4 h-4"/><span className="truncate">{i.id==='adminSettings'?i.key:t(i.key)}</span></button>})}</nav></div>})}</div><div className="p-3 border-t border-[#1F1F22]"><div className="bg-[#18181B] rounded-lg p-3 text-xs"><b className="text-white">{currentUser?.fullName}</b><div className="text-[10px] mt-1"><span className={syncStatus.status==='ONLINE'?'text-emerald-400':'text-amber-400'}>● {syncStatus.status}</span></div></div></div></aside></>;
};
